language: node_js
node_js: '8'
branches:
  only:
  - master
  - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn run generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  verbose: true
  on:
    branch: master

after_success:
  - yarn run lh -- --pwa=80 --perf=80 --seo=80 --a11y=80 --bp=80 https://www.mazipan.xyz
